#pragma once

#include <windows.h>

typedef struct USERENV_PROXY_EXPORT_ENTRY_TAG
{
    const char* procName;
    WORD ordinal;
} USERENV_PROXY_EXPORT_ENTRY;

#define USERENV_PROXY_EXPORT_COUNT 79

static const USERENV_PROXY_EXPORT_ENTRY g_UserenvProxyExports[USERENV_PROXY_EXPORT_COUNT] = {
    { NULL, 104 },
    { "RsopLoggingEnabled", 105 },
    { "AreThereVisibleLogoffScripts", 106 },
    { "AreThereVisibleShutdownScripts", 107 },
    { "CreateAppContainerProfile", 108 },
    { "CreateEnvironmentBlock", 109 },
    { "CreateProfile", 110 },
    { "DeleteAppContainerProfile", 111 },
    { "DeleteProfileA", 112 },
    { "DeleteProfileW", 113 },
    { "DeriveAppContainerSidFromAppContainerName", 114 },
    { "DeriveRestrictedAppContainerSidFromAppContainerSidAndRestrictedName", 115 },
    { "DestroyEnvironmentBlock", 116 },
    { "DllCanUnloadNow", 117 },
    { "DllGetClassObject", 118 },
    { "DllRegisterServer", 119 },
    { "DllUnregisterServer", 120 },
    { "EnterCriticalPolicySection", 121 },
    { NULL, 122 },
    { "ExpandEnvironmentStringsForUserA", 123 },
    { "ExpandEnvironmentStringsForUserW", 124 },
    { "ForceSyncFgPolicy", 125 },
    { "FreeGPOListA", 126 },
    { "FreeGPOListW", 127 },
    { "GenerateGPNotification", 128 },
    { "GetAllUsersProfileDirectoryA", 129 },
    { "GetAllUsersProfileDirectoryW", 130 },
    { "GetAppContainerFolderPath", 131 },
    { "GetAppContainerRegistryLocation", 132 },
    { "GetAppliedGPOListA", 133 },
    { "GetAppliedGPOListW", 134 },
    { NULL, 135 },
    { "GetDefaultUserProfileDirectoryA", 136 },
    { NULL, 137 },
    { "GetDefaultUserProfileDirectoryW", 138 },
    { NULL, 139 },
    { "GetGPOListA", 140 },
    { "GetGPOListW", 141 },
    { "GetNextFgPolicyRefreshInfo", 142 },
    { "GetPreviousFgPolicyRefreshInfo", 143 },
    { "GetProfileType", 144 },
    { "GetProfilesDirectoryA", 145 },
    { "GetProfilesDirectoryW", 146 },
    { "GetUserProfileDirectoryA", 147 },
    { "GetUserProfileDirectoryW", 148 },
    { "HasPolicyForegroundProcessingCompleted", 149 },
    { "LeaveCriticalPolicySection", 150 },
    { "LoadProfileExtender", 151 },
    { "LoadUserProfileA", 152 },
    { "LoadUserProfileW", 153 },
    { "ProcessGroupPolicyCompleted", 154 },
    { "ProcessGroupPolicyCompletedEx", 155 },
    { "RefreshPolicy", 156 },
    { "RefreshPolicyEx", 157 },
    { "RegisterGPNotification", 158 },
    { "RsopAccessCheckByType", 159 },
    { "RsopFileAccessCheck", 160 },
    { "RsopResetPolicySettingStatus", 161 },
    { "RsopSetPolicySettingStatus", 162 },
    { "UnloadProfileExtender", 163 },
    { "UnloadUserProfile", 164 },
    { "UnregisterGPNotification", 165 },
    { "WaitForMachinePolicyForegroundProcessing", 166 },
    { "WaitForUserPolicyForegroundProcessing", 167 },
    { NULL, 175 },
    { NULL, 202 },
    { NULL, 203 },
    { NULL, 206 },
    { NULL, 207 },
    { NULL, 208 },
    { NULL, 209 },
    { NULL, 210 },
    { NULL, 211 },
    { NULL, 212 },
    { NULL, 213 },
    { NULL, 214 },
    { NULL, 217 },
    { NULL, 218 },
    { NULL, 219 },
};
